// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Party.Infrastructure.Data;

#nullable disable

namespace Party.Infrastructure.Migrations
{
    [DbContext(typeof(PartyDbContext))]
    [Migration("20260208141155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Party.Domain.Entities.Party", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Parties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(156),
                            Email = "john.author@library.com",
                            FirstName = "John",
                            LastName = "Author",
                            UpdatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(466)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(816),
                            Email = "jane.customer@library.com",
                            FirstName = "Jane",
                            LastName = "Customer",
                            UpdatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(817)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(819),
                            Email = "bob.both@library.com",
                            FirstName = "Bob",
                            LastName = "Both",
                            UpdatedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(820)
                        });
                });

            modelBuilder.Entity("Party.Domain.Entities.PartyRole", b =>
                {
                    b.Property<Guid>("PartyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PartyId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PartyRoles");

                    b.HasData(
                        new
                        {
                            PartyId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(2376)
                        },
                        new
                        {
                            PartyId = new Guid("44444444-4444-4444-4444-444444444444"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(2679)
                        },
                        new
                        {
                            PartyId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(2682)
                        },
                        new
                        {
                            PartyId = new Guid("55555555-5555-5555-5555-555555555555"),
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            AssignedAt = new DateTime(2026, 2, 8, 14, 11, 54, 419, DateTimeKind.Utc).AddTicks(2683)
                        });
                });

            modelBuilder.Entity("Party.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Author"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("Party.Domain.Entities.PartyRole", b =>
                {
                    b.HasOne("Party.Domain.Entities.Party", "Party")
                        .WithMany("PartyRoles")
                        .HasForeignKey("PartyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Party.Domain.Entities.Role", "Role")
                        .WithMany("PartyRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Party");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Party.Domain.Entities.Party", b =>
                {
                    b.Navigation("PartyRoles");
                });

            modelBuilder.Entity("Party.Domain.Entities.Role", b =>
                {
                    b.Navigation("PartyRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
